/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.samples.fbo.oidc.sid.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.samples.fbo.oidc.sid.model.OidcSid;
import com.liferay.samples.fbo.oidc.sid.model.OidcSidModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OidcSid service. Represents a row in the &quot;OIDCSID_OidcSid&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OidcSidModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OidcSidImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OidcSidImpl
 * @generated
 */
@JSON(strict = true)
public class OidcSidModelImpl
	extends BaseModelImpl<OidcSid> implements OidcSidModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a oidc sid model instance should use the <code>OidcSid</code> interface instead.
	 */
	public static final String TABLE_NAME = "OIDCSID_OidcSid";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"OidcSidId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"openIdConnectSessionId", Types.BIGINT}, {"sid", Types.VARCHAR},
		{"jwksUri", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("OidcSidId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("openIdConnectSessionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("jwksUri", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OIDCSID_OidcSid (uuid_ VARCHAR(75) null,OidcSidId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,openIdConnectSessionId LONG,sid VARCHAR(75) null,jwksUri VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table OIDCSID_OidcSid";

	public static final String ORDER_BY_JPQL =
		" ORDER BY oidcSid.OidcSidId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OIDCSID_OidcSid.OidcSidId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long OPENIDCONNECTSESSIONID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long OIDCSIDID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public OidcSidModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _OidcSidId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOidcSidId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _OidcSidId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OidcSid.class;
	}

	@Override
	public String getModelClassName() {
		return OidcSid.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OidcSid, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OidcSid, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OidcSid, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((OidcSid)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OidcSid, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OidcSid, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OidcSid)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OidcSid, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OidcSid, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<OidcSid, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<OidcSid, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<OidcSid, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<OidcSid, Object>>();
		Map<String, BiConsumer<OidcSid, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<OidcSid, ?>>();

		attributeGetterFunctions.put("uuid", OidcSid::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<OidcSid, String>)OidcSid::setUuid);
		attributeGetterFunctions.put("OidcSidId", OidcSid::getOidcSidId);
		attributeSetterBiConsumers.put(
			"OidcSidId", (BiConsumer<OidcSid, Long>)OidcSid::setOidcSidId);
		attributeGetterFunctions.put("companyId", OidcSid::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<OidcSid, Long>)OidcSid::setCompanyId);
		attributeGetterFunctions.put("userId", OidcSid::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<OidcSid, Long>)OidcSid::setUserId);
		attributeGetterFunctions.put("userName", OidcSid::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<OidcSid, String>)OidcSid::setUserName);
		attributeGetterFunctions.put("createDate", OidcSid::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<OidcSid, Date>)OidcSid::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", OidcSid::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<OidcSid, Date>)OidcSid::setModifiedDate);
		attributeGetterFunctions.put(
			"openIdConnectSessionId", OidcSid::getOpenIdConnectSessionId);
		attributeSetterBiConsumers.put(
			"openIdConnectSessionId",
			(BiConsumer<OidcSid, Long>)OidcSid::setOpenIdConnectSessionId);
		attributeGetterFunctions.put("sid", OidcSid::getSid);
		attributeSetterBiConsumers.put(
			"sid", (BiConsumer<OidcSid, String>)OidcSid::setSid);
		attributeGetterFunctions.put("jwksUri", OidcSid::getJwksUri);
		attributeSetterBiConsumers.put(
			"jwksUri", (BiConsumer<OidcSid, String>)OidcSid::setJwksUri);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getOidcSidId() {
		return _OidcSidId;
	}

	@Override
	public void setOidcSidId(long OidcSidId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_OidcSidId = OidcSidId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getOpenIdConnectSessionId() {
		return _openIdConnectSessionId;
	}

	@Override
	public void setOpenIdConnectSessionId(long openIdConnectSessionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_openIdConnectSessionId = openIdConnectSessionId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalOpenIdConnectSessionId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("openIdConnectSessionId"));
	}

	@JSON
	@Override
	public String getSid() {
		if (_sid == null) {
			return "";
		}
		else {
			return _sid;
		}
	}

	@Override
	public void setSid(String sid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sid = sid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalSid() {
		return getColumnOriginalValue("sid");
	}

	@JSON
	@Override
	public String getJwksUri() {
		if (_jwksUri == null) {
			return "";
		}
		else {
			return _jwksUri;
		}
	}

	@Override
	public void setJwksUri(String jwksUri) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_jwksUri = jwksUri;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(OidcSid.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), OidcSid.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OidcSid toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OidcSid>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OidcSidImpl oidcSidImpl = new OidcSidImpl();

		oidcSidImpl.setUuid(getUuid());
		oidcSidImpl.setOidcSidId(getOidcSidId());
		oidcSidImpl.setCompanyId(getCompanyId());
		oidcSidImpl.setUserId(getUserId());
		oidcSidImpl.setUserName(getUserName());
		oidcSidImpl.setCreateDate(getCreateDate());
		oidcSidImpl.setModifiedDate(getModifiedDate());
		oidcSidImpl.setOpenIdConnectSessionId(getOpenIdConnectSessionId());
		oidcSidImpl.setSid(getSid());
		oidcSidImpl.setJwksUri(getJwksUri());

		oidcSidImpl.resetOriginalValues();

		return oidcSidImpl;
	}

	@Override
	public OidcSid cloneWithOriginalValues() {
		OidcSidImpl oidcSidImpl = new OidcSidImpl();

		oidcSidImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		oidcSidImpl.setOidcSidId(
			this.<Long>getColumnOriginalValue("OidcSidId"));
		oidcSidImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		oidcSidImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		oidcSidImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		oidcSidImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		oidcSidImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		oidcSidImpl.setOpenIdConnectSessionId(
			this.<Long>getColumnOriginalValue("openIdConnectSessionId"));
		oidcSidImpl.setSid(this.<String>getColumnOriginalValue("sid"));
		oidcSidImpl.setJwksUri(this.<String>getColumnOriginalValue("jwksUri"));

		return oidcSidImpl;
	}

	@Override
	public int compareTo(OidcSid oidcSid) {
		long primaryKey = oidcSid.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OidcSid)) {
			return false;
		}

		OidcSid oidcSid = (OidcSid)object;

		long primaryKey = oidcSid.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<OidcSid> toCacheModel() {
		OidcSidCacheModel oidcSidCacheModel = new OidcSidCacheModel();

		oidcSidCacheModel.uuid = getUuid();

		String uuid = oidcSidCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			oidcSidCacheModel.uuid = null;
		}

		oidcSidCacheModel.OidcSidId = getOidcSidId();

		oidcSidCacheModel.companyId = getCompanyId();

		oidcSidCacheModel.userId = getUserId();

		oidcSidCacheModel.userName = getUserName();

		String userName = oidcSidCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			oidcSidCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			oidcSidCacheModel.createDate = createDate.getTime();
		}
		else {
			oidcSidCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			oidcSidCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			oidcSidCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		oidcSidCacheModel.openIdConnectSessionId = getOpenIdConnectSessionId();

		oidcSidCacheModel.sid = getSid();

		String sid = oidcSidCacheModel.sid;

		if ((sid != null) && (sid.length() == 0)) {
			oidcSidCacheModel.sid = null;
		}

		oidcSidCacheModel.jwksUri = getJwksUri();

		String jwksUri = oidcSidCacheModel.jwksUri;

		if ((jwksUri != null) && (jwksUri.length() == 0)) {
			oidcSidCacheModel.jwksUri = null;
		}

		return oidcSidCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OidcSid, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OidcSid, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OidcSid, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((OidcSid)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OidcSid>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					OidcSid.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _OidcSidId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _openIdConnectSessionId;
	private String _sid;
	private String _jwksUri;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<OidcSid, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((OidcSid)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("OidcSidId", _OidcSidId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"openIdConnectSessionId", _openIdConnectSessionId);
		_columnOriginalValues.put("sid", _sid);
		_columnOriginalValues.put("jwksUri", _jwksUri);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("OidcSidId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("openIdConnectSessionId", 128L);

		columnBitmasks.put("sid", 256L);

		columnBitmasks.put("jwksUri", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private OidcSid _escapedModel;

}